describe('dia',()=>{
    it('gonis',()=>{
    
    cy.visit('https://vetcastle.com')
    cy.get('.grow > :nth-child(2) > .font-medium').click()
    cy.get('.justify-center > :nth-child(3)').click()
    cy.get('#username').type('naveen')
    cy.get('#password').type('NAVEEn@3445')
    cy.get('.btn').click()
    cy.wait(1000)
    cy.reload()
    cy.get('[href="/inventory"] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('.MuiGrid-container > :nth-child(3) > .MuiButtonBase-root').click()
    cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="10"]').click()
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(2)').type('0001')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(3)').type('health food')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(4)').type('00091')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(5)').type('39')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(6)').type('nothing')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(7)').type('no')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(8)').type('yes')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(9)').type('20%')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(10)').type('455')
cy.get('[data-testid="SaveIcon"]').click()
    })
})