describe('hospital',()=>{
    it('create',()=>{
    cy.visit('https://vetcastle.com')
    cy.get('.grow > :nth-child(2) > .font-medium').click()
    cy.get('.justify-center > :nth-child(3)').click()
cy.get('#username').type('naveen')
cy.get('#password').type('NAVEEn@3445')
cy.get('.btn').click()
cy.wait(1000)
cy.reload()
cy.get('.MuiToolbar-root > .MuiTypography-root').click()
cy.url().should('eq','https://vetcastle.com/maindashboard')
cy.get('[href="/hsd"] > .MuiListItemText-root > .MuiTypography-root').click()
cy.url().should('eq','https://vetcastle.com/hsd')
cy.get('.MuiGrid-container > :nth-child(3) > .MuiButtonBase-root').click()
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(1)').type('naveenkumarm')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(2)').type('NAVEEn@3445')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(3)').type('naveen')
cy.get('.MuiGrid-container > :nth-child(4)').type('Kumar')
cy.get('.MuiGrid-container > :nth-child(5)').click()
cy.get('[data-value="male"]').click()
cy.get(':nth-child(6) > .react-tel-input > .form-control').type('9344611084')
cy.get(':nth-child(7) > .react-tel-input > .form-control').type('9751372618')
cy.get('.MuiGrid-container > :nth-child(8)').type('naveenkumar20030807@mail.com')
cy.get('.MuiGrid-container > :nth-child(9)').type("2003-08-07")
cy.get('.MuiGrid-container > :nth-child(10)').type('3/62-1 mudhugampatti')
cy.get(':nth-child(11) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="IN"]').click()
cy.get(':nth-child(12) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="TN"]').click()
cy.get(':nth-child(13) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="Dharmapuri"]').click()
cy.get('.MuiGrid-container > :nth-child(14)').type('636810')
cy.get('.MuiGrid-container > :nth-child(17)').type('Platium')
cy.get('.MuiGrid-container > :nth-child(18)').click()
cy.get('[data-testid="SaveIcon"]').click()
cy.get('[data-id="100001"] > [data-field="action"] > .cellAction > .viewbutton').click()
cy.get('[data-testid="EditIcon"]').click()
cy.get('.MuiDialogContent-root > :nth-child(2) > :nth-child(4)').clear().type('naveen murali')
cy.get('.MuiDialogContent-root > :nth-child(2) > :nth-child(5)').clear().type('naveen')
cy.get('.MuiDialogContent-root > :nth-child(2) > :nth-child(6)').clear().type('murali')
cy.get(':nth-child(2) > :nth-child(7)').clear().type('09876544321')
cy.get(':nth-child(2) > :nth-child(8)').clear().type('1234567890')
cy.get(':nth-child(2) > :nth-child(9)').clear().type('murali@345')
cy.get('[data-testid="DeleteIcon"]').click()
    })
})