describe('user',()=>{
it('name',()=>{
cy.visit('https://vetcastle.com')
cy.get('.grow > :nth-child(2) > .font-medium').click()
cy.get('.justify-center > :nth-child(3)').click()
cy.get('#username').type('naveen')
cy.get('#password').type('NAVEEn@3445')
cy.get('.btn').click()
cy.wait(1000)
cy.reload()
cy.get('.MuiToolbar-root > .MuiTypography-root').click()
cy.url().should('eq','https://vetcastle.com/maindashboard')
cy.get('[href="/asd"] > .MuiListItemText-root > .MuiTypography-root').click()
cy.url().should('eq','https://vetcastle.com/asd')
cy.get('.MuiGrid-container > :nth-child(3) > .MuiButtonBase-root').click()

cy.get(':nth-child(1) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="400001"]').click()
cy.get(':nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="300001"]').click()
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(3)').click()
cy.get(':nth-child(39)').click()
cy.get('.MuiGrid-container > :nth-child(4)').type( 'sickness')
cy.get('.MuiGrid-container > :nth-child(5)').click()
cy.get('.MuiGrid-container > :nth-child(5)').type('06/06/2024 12:00 AM')
///cy.get('.MuiInputAdornment-root > .MuiButtonBase-root').click().select('[data-timestamp="1717525800000"]')
//cy.get('[data-timestamp="1717525800000"]').select()
///cy.get('[value="06/06/2024 12:00 AM"]').click()
///cy.get('.MuiInputAdornment-root > .MuiButtonBase-root').select("04/23/2023 ")

cy.get('[data-testid="SaveIcon"]').click()

})

})