describe('user',()=>{
    it('name',()=>{
    cy.visit('https://vetcastle.com')
    cy.get('.grow > :nth-child(2) > .font-medium').click()
    cy.get('.justify-center > :nth-child(3)').click()
    cy.get('#username').type('naveen')
    cy.get('#password').type('NAVEEn@3445')
    cy.get('.btn').click()
    cy.wait(1000)
    cy.reload()
    cy.get('[href="/psd"] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-id="500011"] > .MuiDataGrid-cell--withRenderer > .cellAction > .viewbutton').click()
cy.get('[data-testid="EditIcon"]').click()
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(2)').clear().type('july')
cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(2)').should('contain.text','Pet Name')
cy.get('.MuiGrid-container > :nth-child(4)').clear().type('12')
cy.get('.MuiGrid-container > :nth-child(4)').should('contain.text','Age')
cy.get('.MuiGrid-container > :nth-child(5)').clear().type('7.00')
cy.get('.MuiGrid-container > :nth-child(5)').should('contain.text','Weight')
cy.get('.MuiGrid-container > :nth-child(7)').clear().type('2024-08-07')
cy.get('.MuiGrid-container > :nth-child(7)').should('contain.text','Last Vet Visit')
cy.get('.MuiGrid-container > :nth-child(8)').clear().type('2003-08-07')
cy.get('.MuiGrid-container > :nth-child(8)').should('contain.text','Next Vet Visit')
cy.get('.MuiGrid-container > :nth-child(9)').clear().type('Dvs Food')
cy.get('.MuiGrid-container > :nth-child(9)').should('contain.text','Food Brand')
cy.get('.MuiGrid-container > :nth-child(10)').clear().type('500')
cy.get('.MuiGrid-container > :nth-child(10)').should('contain.text','Food Amount')
cy.get(':nth-child(11) > .MuiInputBase-root > .MuiSelect-select').click()
cy.get('[data-value="male"]').click()
cy.get(':nth-child(12) > .MuiInputBase-root > .MuiSelect-select').click()
    cy.get('[data-value="wet"]').click()
    cy.get('[data-testid="SaveIcon"]').click()
})
})